//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class homesteadEntities : DbContext
    {
        public homesteadEntities()
            : base("name=homesteadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<brand> brand { get; set; }
        public virtual DbSet<building> building { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<factory> factory { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<order_detail> order_detail { get; set; }
        public virtual DbSet<vehicle_model> vehicle_model { get; set; }
        public virtual DbSet<vehicle_part> vehicle_part { get; set; }
        public virtual DbSet<vehicle_type> vehicle_type { get; set; }
        public virtual DbSet<color> color { get; set; }
        public virtual DbSet<vehicle_motor> vehicle_motor { get; set; }
    }
}
